/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ShareManager;

import javax.swing.JTable;

/**
 * @author opossum
 */
public class NewShare extends javax.swing.JFrame {
    JTable sm;
    boolean update; //új rekord, vagy módosítás
    Integer id;
    DB db = new DB();
    
    /**
     * Creates new form MainWindow
     */
    public NewShare() {
        initComponents();
        
        update = false; //új rekord
        
        Config.addItemToComboBox(cbxExchangeName, db.sqlBeolvasOszlopot(Config.tablesNameSQL[4])); 
        Config.addItemToComboBox(cbxType, db.sqlBeolvasOszlopot(Config.tablesNameSQL[0])); 
        Config.addItemToComboBox(cbxCurrency, db.sqlBeolvasOszlopot(Config.tablesNameSQL[2]));
    }
    
    public void loadData(String[] s, int id){
        this.id = id;
        lbID.setText(this.id.toString());
        txtShareName.setText(s[0]);
        txtCompanyName.setText(s[1]);
        txtISINcode.setText(s[4]);
        cbxCurrency.setSelectedItem(s[5]);
        cbxExchangeName.setSelectedItem(s[2]);
        cbxType.setSelectedItem(s[3]);
        lbHeader.setText("Értékpapír módosítása");
        update = true; //rekordot módosít
    }
    
    private boolean OK() {

        String shareName = txtShareName.getText();
        String companyName = txtCompanyName.getText();
        String exchangeName = db.sqlBeolvasMezot(4, cbxExchangeName.getSelectedItem().toString());
        String type = db.sqlBeolvasMezot(0, cbxType.getSelectedItem().toString());
        String isin = txtISINcode.getText();
        String currency = db.sqlBeolvasMezot(2, cbxCurrency.getSelectedItem().toString());

        String[] s = {shareName,companyName,exchangeName,type,isin,currency};

        DB db = new DB();
        if (update) db.sqlUpdateRow(1, id, s);
        else db.sqlInsertRow(Config.tablesNameSQL[1], s);
        ShareManager.mainWindow.tablazatFrissites();
        this.dispose();
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        cbxCurrency = new javax.swing.JComboBox<>();
        btCancel = new javax.swing.JButton();
        cbxExchangeName = new javax.swing.JComboBox<>();
        btOK = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtShareName = new javax.swing.JTextField();
        lbHeader = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbxType = new javax.swing.JComboBox<>();
        txtISINcode = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btNewMulti3 = new javax.swing.JButton();
        btNewMulti1 = new javax.swing.JButton();
        btNewMulti0 = new javax.swing.JButton();
        lbID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Share");
        setSize(new java.awt.Dimension(800, 600));

        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbxCurrency.setToolTipText("");

        btCancel.setMnemonic('m');
        btCancel.setText("Mégse");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        btOK.setMnemonic('o');
        btOK.setText("OK");
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });

        jLabel6.setText("Rövid név (Ticker)");

        jLabel7.setText("Tőzsde");

        jLabel10.setText("Pénznem");

        txtShareName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtShareName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShareNameActionPerformed(evt);
            }
        });

        lbHeader.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHeader.setText("Új értékpapír");

        jLabel8.setText("Vállalat neve");

        txtCompanyName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyNameActionPerformed(evt);
            }
        });

        jLabel9.setText("Típus");

        txtISINcode.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtISINcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISINcodeActionPerformed(evt);
            }
        });

        jLabel11.setText("ISIN kód");

        btNewMulti3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btNewMulti3.setText("+");
        btNewMulti3.setAlignmentY(0.0F);
        btNewMulti3.setBorder(null);
        btNewMulti3.setBorderPainted(false);
        btNewMulti3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btNewMulti3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewMulti3ActionPerformed(evt);
            }
        });

        btNewMulti1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btNewMulti1.setText("+");
        btNewMulti1.setAlignmentY(0.0F);
        btNewMulti1.setBorder(null);
        btNewMulti1.setBorderPainted(false);
        btNewMulti1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btNewMulti1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewMulti1ActionPerformed(evt);
            }
        });

        btNewMulti0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btNewMulti0.setText("+");
        btNewMulti0.setAlignmentY(0.0F);
        btNewMulti0.setBorder(null);
        btNewMulti0.setBorderPainted(false);
        btNewMulti0.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btNewMulti0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewMulti0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btOK, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panel1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panel1Layout.createSequentialGroup()
                                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(panel1Layout.createSequentialGroup()
                                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel8))
                                                    .addGap(32, 32, 32))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(btNewMulti0, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(panel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel7)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btNewMulti1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(panel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel9)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btNewMulti3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cbxType, 0, 147, Short.MAX_VALUE)
                                                .addComponent(cbxCurrency, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbxExchangeName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtShareName)
                                                .addComponent(txtCompanyName)
                                                .addComponent(txtISINcode, javax.swing.GroupLayout.Alignment.TRAILING)))))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbID, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtShareName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxExchangeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNewMulti1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNewMulti3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtISINcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbxCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNewMulti0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancel)
                    .addComponent(btOK))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtShareNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShareNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShareNameActionPerformed

    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed
        OK();
    }//GEN-LAST:event_btOKActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void txtCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyNameActionPerformed

    private void txtISINcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISINcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISINcodeActionPerformed

    private void btNewMulti3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewMulti3ActionPerformed
        NewMulti nm = new NewMulti(0);
        nm.setVisible(true);
    }//GEN-LAST:event_btNewMulti3ActionPerformed

    private void btNewMulti1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewMulti1ActionPerformed
        NewMulti nm = new NewMulti(4);
        nm.setVisible(true);
    }//GEN-LAST:event_btNewMulti1ActionPerformed

    private void btNewMulti0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewMulti0ActionPerformed
        NewMulti nm = new NewMulti(2);
        nm.setVisible(true);
    }//GEN-LAST:event_btNewMulti0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static boolean main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShareManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShareManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShareManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShareManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private static javax.swing.JButton btNewMulti0;
    private static javax.swing.JButton btNewMulti1;
    private static javax.swing.JButton btNewMulti3;
    private javax.swing.JButton btOK;
    private javax.swing.JComboBox<String> cbxCurrency;
    private javax.swing.JComboBox<String> cbxExchangeName;
    private javax.swing.JComboBox<String> cbxType;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbHeader;
    private javax.swing.JLabel lbID;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtISINcode;
    private javax.swing.JTextField txtShareName;
    // End of variables declaration//GEN-END:variables
}
