/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ShareManager;

import Panels.Ertekpapirok;
import Panels.Kimutatas;
import Panels.Panel;
import Panels.Penznemek;
import Panels.Szamlak;
import Panels.Tipusok;
import Panels.Tozsdek;
import Panels.Ugyletek;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JFrame;

/**
 * @author opossum
 * 2018 szakdolgozatra
 */
public class ShareManager extends javax.swing.JFrame {

    public static ShareManager mainWindow;
    
    GridBagLayout layout = new GridBagLayout();
    Panel tozsdek;
    Panel penznemek;
    Panel ertekpapirok;
    Panel tipusok;
    Panel szamlak;
    Panel ugyletek;
    Panel kimutatas;
    
    /**
     * Creates new form MainWindow
     */
    public ShareManager() {
        initComponents();
        if (Config.FullScreen) this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);      
        
        tozsdek = new Tozsdek();
        penznemek = new Penznemek();
        tipusok = new Tipusok();
        szamlak = new Szamlak();
        ertekpapirok = new Ertekpapirok();
        ugyletek = new Ugyletek();
        kimutatas = new Kimutatas();
        dynamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        dynamicPanel.add(tozsdek, c);
        dynamicPanel.add(penznemek, c);
        dynamicPanel.add(ertekpapirok, c);
        dynamicPanel.add(tipusok, c);
        dynamicPanel.add(szamlak, c);
        dynamicPanel.add(ugyletek, c);
        dynamicPanel.add(kimutatas, c);
        setDynamicPanel(null);
    }
    
    private void setDynamicPanel(Panel p) {
        tozsdek.setVisible(false);
        penznemek.setVisible(false);
        ertekpapirok.setVisible(false);
        tipusok.setVisible(false);
        szamlak.setVisible(false);
        ugyletek.setVisible(false);
        kimutatas.setVisible(false);
  
        if (p!=null) {
            p.frissites();
            p.setVisible(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dynamicPanel = new javax.swing.JPanel();
        menu = new javax.swing.JMenuBar();
        mUgyletek = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mTorzsadatok = new javax.swing.JMenu();
        miTozsdek = new javax.swing.JMenuItem();
        miErtekpapirok = new javax.swing.JMenuItem();
        miTipusok = new javax.swing.JMenuItem();
        miPenznemek = new javax.swing.JMenuItem();
        miSzamlak = new javax.swing.JMenuItem();
        mBeallitasok = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Share Manager");
        setMinimumSize(new java.awt.Dimension(800, 620));
        setSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout dynamicPanelLayout = new javax.swing.GroupLayout(dynamicPanel);
        dynamicPanel.setLayout(dynamicPanelLayout);
        dynamicPanelLayout.setHorizontalGroup(
            dynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        dynamicPanelLayout.setVerticalGroup(
            dynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        mUgyletek.setMnemonic('K');
        mUgyletek.setText("Kereskedés");

        jMenuItem1.setMnemonic('\u00fc');
        jMenuItem1.setText("Ügyletek");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mUgyletek.add(jMenuItem1);

        jMenuItem2.setMnemonic('k');
        jMenuItem2.setText("Kimutatások");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mUgyletek.add(jMenuItem2);

        menu.add(mUgyletek);

        mTorzsadatok.setMnemonic('t');
        mTorzsadatok.setText("Törzsadatok");
        mTorzsadatok.setToolTipText("");

        miTozsdek.setText("Tőzsdék");
        miTozsdek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTozsdekActionPerformed(evt);
            }
        });
        mTorzsadatok.add(miTozsdek);

        miErtekpapirok.setText("Értékpapírok");
        miErtekpapirok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miErtekpapirokActionPerformed(evt);
            }
        });
        mTorzsadatok.add(miErtekpapirok);

        miTipusok.setText("Típusok");
        miTipusok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTipusokActionPerformed(evt);
            }
        });
        mTorzsadatok.add(miTipusok);

        miPenznemek.setText("Pénznemek");
        miPenznemek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPenznemekActionPerformed(evt);
            }
        });
        mTorzsadatok.add(miPenznemek);

        miSzamlak.setText("Számlák");
        miSzamlak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSzamlakActionPerformed(evt);
            }
        });
        mTorzsadatok.add(miSzamlak);

        menu.add(mTorzsadatok);

        mBeallitasok.setMnemonic('b');
        mBeallitasok.setText("Beállítások");

        jMenuItem3.setMnemonic('E');
        jMenuItem3.setText("Ez legyen a kezdőoldal");
        mBeallitasok.add(jMenuItem3);

        jMenuItem4.setMnemonic('R');
        jMenuItem4.setText("Üres kezdőoldal");
        mBeallitasok.add(jMenuItem4);

        menu.add(mBeallitasok);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miTozsdekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTozsdekActionPerformed
        setDynamicPanel(tozsdek);
    }//GEN-LAST:event_miTozsdekActionPerformed

    private void miPenznemekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPenznemekActionPerformed
        setDynamicPanel(penznemek);
    }//GEN-LAST:event_miPenznemekActionPerformed

    private void miErtekpapirokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miErtekpapirokActionPerformed
        setDynamicPanel(ertekpapirok);
    }//GEN-LAST:event_miErtekpapirokActionPerformed

    private void miTipusokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTipusokActionPerformed
        setDynamicPanel(tipusok);
    }//GEN-LAST:event_miTipusokActionPerformed

    private void miSzamlakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSzamlakActionPerformed
        setDynamicPanel(szamlak);
    }//GEN-LAST:event_miSzamlakActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        setDynamicPanel(ugyletek);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        setDynamicPanel(kimutatas);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShareManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShareManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShareManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShareManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    
    /**
     * A LogIn-ból ezzel a metódussal "indul el" a program
     */
    public static void stratShareManager(){
        mainWindow = new ShareManager();
        mainWindow.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu mBeallitasok;
    private javax.swing.JMenu mTorzsadatok;
    private javax.swing.JMenu mUgyletek;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem miErtekpapirok;
    private javax.swing.JMenuItem miPenznemek;
    private javax.swing.JMenuItem miSzamlak;
    private javax.swing.JMenuItem miTipusok;
    private javax.swing.JMenuItem miTozsdek;
    // End of variables declaration//GEN-END:variables
}
