/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ShareManager;

import java.time.LocalDateTime;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 * @author opossum
 * 2018 szakdolgozatra
 */
public class ShareManager extends javax.swing.JFrame {

    static ShareManager mainWindow;
    static String user;
    int currentTable = 1;
    ListSelectionModel selectionModel;
    
    DB db = new DB();
    
    String date = LocalDateTime.now().toString().substring(0, 10);
    
    /**
     * Creates new form MainWindow
     */
    public ShareManager() {
        initComponents();
        if (Config.FullScreen) this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);      
        
        setTableSelctionModel();
        tablazatFrissites();
        setVisible(true);
    }
    
    public DefaultTableModel getTableDefaultModel(){
        return (DefaultTableModel)table.getModel();
    }
    
    /*
    *Beállítja a Selection modelt, így csak akkor elérhető a módosító és törlő gomb, ha ki van jelölve egy sor
    */
    private void setTableSelctionModel(){
        selectionModel = table.getSelectionModel();
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if (!selectionModel.isSelectionEmpty()) {
                    btChangeRecord.setEnabled(true);
                    btDeleteRecord.setEnabled(true);
                } else {
                    btChangeRecord.setEnabled(false);
                    btDeleteRecord.setEnabled(false);
                }
            }
        });
    }
    
    /**
     * A megadott paraméter alapján létrehozza, frissíti a táblázatot.
     * @param t a ShareManager.tables tömb egy sorszáma
     */
    public void tablazatFrissites() {
        lbTableName.setText(Config.tablesNameForm[currentTable]);
        try {
            db.sqlBeolvasTablat(table, currentTable);
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(this,"A hivatkozott tábla nem szerepel a table tömbben","Hiba",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btPosition = new javax.swing.JButton();
        btExchange = new javax.swing.JButton();
        btCurrency = new javax.swing.JButton();
        btShare = new javax.swing.JButton();
        btAccount = new javax.swing.JButton();
        btType = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        lbTableName = new javax.swing.JLabel();
        btAddNewRecord = new javax.swing.JButton();
        btChangeRecord = new javax.swing.JButton();
        btDeleteRecord = new javax.swing.JButton();
        btRefresh = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Share Manager");
        setSize(new java.awt.Dimension(800, 600));

        panMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panMenu.setMaximumSize(new java.awt.Dimension(100, 600));
        panMenu.setPreferredSize(new java.awt.Dimension(100, 600));
        panMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Menü");
        panMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        btPosition.setText("Ügyletek");
        btPosition.setName(""); // NOI18N
        btPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPositionActionPerformed(evt);
            }
        });
        panMenu.add(btPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, -1));
        btPosition.getAccessibleContext().setAccessibleName("ugyletek");

        btExchange.setText("Tőzsdék");
        btExchange.setName("tozsdek"); // NOI18N
        btExchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExchangeActionPerformed(evt);
            }
        });
        panMenu.add(btExchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, -1));

        btCurrency.setText("Devizák");
        btCurrency.setName("penznemek"); // NOI18N
        btCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCurrencyActionPerformed(evt);
            }
        });
        panMenu.add(btCurrency, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, -1));

        btShare.setText("Értékpapírok");
        btShare.setName(""); // NOI18N
        btShare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShareActionPerformed(evt);
            }
        });
        panMenu.add(btShare, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, -1));
        btShare.getAccessibleContext().setAccessibleName("ertekpapirok");

        btAccount.setText("Számlák");
        btAccount.setName("szamlak"); // NOI18N
        btAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAccountActionPerformed(evt);
            }
        });
        panMenu.add(btAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 130, -1));

        btType.setText("Értékpapír típusok");
        btType.setName("ertekpapir_tipusok"); // NOI18N
        btType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTypeActionPerformed(evt);
            }
        });
        panMenu.add(btType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 130, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "null", "null", "null", "null", "null", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        lbTableName.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lbTableName.setText("Táblázat");

        btAddNewRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btAddNewRecord.setToolTipText("Új hozzáadása");
        btAddNewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddNewRecordActionPerformed(evt);
            }
        });

        btChangeRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/change.png"))); // NOI18N
        btChangeRecord.setToolTipText("Módosítás");
        btChangeRecord.setEnabled(false);
        btChangeRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChangeRecordActionPerformed(evt);
            }
        });

        btDeleteRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/del.png"))); // NOI18N
        btDeleteRecord.setToolTipText("Törlés");
        btDeleteRecord.setEnabled(false);
        btDeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteRecordActionPerformed(evt);
            }
        });

        btRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        btRefresh.setToolTipText("Frissítés");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAddNewRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btChangeRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btDeleteRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(lbTableName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAddNewRecord, btChangeRecord, btDeleteRecord, btRefresh});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lbTableName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btChangeRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDeleteRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAddNewRecord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btChangeRecord, btDeleteRecord, btRefresh});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPositionActionPerformed
                
    }//GEN-LAST:event_btPositionActionPerformed

    private void btExchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExchangeActionPerformed
        currentTable = 4;
        tablazatFrissites();
    }//GEN-LAST:event_btExchangeActionPerformed

    private void btCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCurrencyActionPerformed
        currentTable = 2;
        tablazatFrissites();
    }//GEN-LAST:event_btCurrencyActionPerformed

    private void btShareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShareActionPerformed
        currentTable = 1;
        tablazatFrissites();
    }//GEN-LAST:event_btShareActionPerformed

    private void btAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAccountActionPerformed
        currentTable = 3;
        tablazatFrissites();
    }//GEN-LAST:event_btAccountActionPerformed

    private void btTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTypeActionPerformed
        currentTable = 0;
        tablazatFrissites();
    }//GEN-LAST:event_btTypeActionPerformed

    private void btAddNewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddNewRecordActionPerformed
        NewMulti nm;
        switch (currentTable) {
            case 0:         //értékpapír típusok
                nm = new NewMulti(0);
                nm.setVisible(true);
                break;
            case 1:         //értékpapírok
                NewShare ns = new NewShare();
                ns.setVisible(true);
                break;
            case 2:         //pénznemek
                nm = new NewMulti(2);
                nm.setVisible(true);
                break;
            case 3:         //számlák
                nm = new NewMulti(3);
                nm.setVisible(true);
                break;
            case 4:         //tőzsdék
                nm = new NewMulti(4);
                nm.setVisible(true);
                break;
        }
    }//GEN-LAST:event_btAddNewRecordActionPerformed

    private void btDeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteRecordActionPerformed
        // Törli az aktuálisan kijelölt sort
        int y = selectionModel.getLeadSelectionIndex();
        y = Integer.valueOf((String) table.getValueAt(y, 0));
        if (0==JOptionPane.showConfirmDialog(this,"Biztos törölni akarja?" + System.lineSeparator() + y + ".azonosító számú rekord?","Megerősítés",0)) {
                db.sqlTorol(Config.tablesNameSQL[currentTable], y);
        } 
        tablazatFrissites();
    }//GEN-LAST:event_btDeleteRecordActionPerformed

    private void btChangeRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChangeRecordActionPerformed
        NewMulti nm;
        int row = table.getSelectedRow();
        int id = Integer.valueOf((String) table.getValueAt(selectionModel.getLeadSelectionIndex(), 0));
        switch (currentTable) {
            case 0:         //értékpapír típusok
                nm = new NewMulti(0);
                nm.loadData(table.getValueAt(row, 1).toString(), null, id);        
                nm.setVisible(true);
                break;
            case 1:         //értékpapírok
                NewShare ns = new NewShare();
                String[] s = new String[6];
                for (int i=0; i<6; i++){
                    s[i] = table.getValueAt(row, i+1).toString();
                }
                ns.loadData(s, id);
                ns.setVisible(true);
                break;
            case 2:         //pénznemek
                nm = new NewMulti(2);
                nm.loadData(table.getValueAt(row, 1).toString(),table.getValueAt(row, 2).toString(),id); 
                nm.setVisible(true);
                break;
            case 3:         //számlák
                nm = new NewMulti(3);
                nm.loadData(table.getValueAt(row, 1).toString(), null, id); 
                nm.setVisible(true);
                break;
            case 4:         //tőzsdék
                nm = new NewMulti(4);
                nm.loadData(table.getValueAt(row, 1).toString(),table.getValueAt(row, 2).toString(),id); 
                nm.setVisible(true);
                break;
        }
    }//GEN-LAST:event_btChangeRecordActionPerformed

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        tablazatFrissites();
    }//GEN-LAST:event_btRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShareManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShareManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShareManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShareManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    
    public static void stratShareManager(){
        mainWindow = new ShareManager();
        mainWindow.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAccount;
    private javax.swing.JButton btAddNewRecord;
    private javax.swing.JButton btChangeRecord;
    private javax.swing.JButton btCurrency;
    private javax.swing.JButton btDeleteRecord;
    private javax.swing.JButton btExchange;
    private javax.swing.JButton btPosition;
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton btShare;
    private javax.swing.JButton btType;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTableName;
    private javax.swing.JPanel panMenu;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
