/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import static Panels.Ertekpapirok.tbErtekpapirok;
import ShareManager.Config;
import ShareManager.DB;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 * @author atna
 */
public class Penznemek extends Panel {
    ListSelectionModel selectionModel;
    
    /**
     * Creates new form Penznemek
     */
    public Penznemek() {
        initComponents();
        frissites();
        Config.textFieldUpper(txtRovidNev);
        Config.textFieldLimit(txtRovidNev, 5);
        Config.textFieldLimit(txtTeljesNev, 30);
        Config.textFieldPopup(txtRovidNev);
        Config.textFieldPopup(txtTeljesNev);
        Config.uniqueTextListener(txtRovidNev, tbPenznemek, btAdd, btUpdate);
    }
    
    public void frissites(){
        DB db = new DB();
        db.sqlLekerdezPenznemek(tbPenznemek);
        setTableListener();
    }
    
    private void setTableListener(){
        selectionModel = tbPenznemek.getSelectionModel();
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if (!selectionModel.isSelectionEmpty()) {
                    btUpdate.setEnabled(true);
                    btDel.setEnabled(true);
                    int i = selectionModel.getMinSelectionIndex();
                    if (!tbPenznemek.getValueAt(i, 1).equals(txtRovidNev.getText())){
                        txtRovidNev.setText(tbPenznemek.getValueAt(i, 1).toString());
                    } else btAdd.setEnabled(false);
                    txtTeljesNev.setText(tbPenznemek.getValueAt(i, 2).toString());
                } else {
                    btUpdate.setEnabled(false);
                    btDel.setEnabled(false);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPenznemek = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRovidNev = new javax.swing.JTextField();
        txtTeljesNev = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btDel = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(540, 480));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pénznemek");

        tbPenznemek.setAutoCreateRowSorter(true);
        tbPenznemek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Pénznem ID", "Rövid név", "Teljes név"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPenznemek.setNextFocusableComponent(txtRovidNev);
        jScrollPane1.setViewportView(tbPenznemek);
        if (tbPenznemek.getColumnModel().getColumnCount() > 0) {
            tbPenznemek.getColumnModel().getColumn(0).setMinWidth(0);
            tbPenznemek.getColumnModel().getColumn(0).setPreferredWidth(0);
            tbPenznemek.getColumnModel().getColumn(0).setMaxWidth(0);
            tbPenznemek.getColumnModel().getColumn(1).setPreferredWidth(30);
        }

        jLabel2.setText("Rövid név");

        jLabel3.setText("Teljes név");

        txtRovidNev.setNextFocusableComponent(txtTeljesNev);
        txtRovidNev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRovidNevActionPerformed(evt);
            }
        });

        txtTeljesNev.setNextFocusableComponent(btAdd);
        txtTeljesNev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeljesNevActionPerformed(evt);
            }
        });

        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/013-add.png"))); // NOI18N
        btAdd.setToolTipText("Hozzáad");
        btAdd.setEnabled(false);
        btAdd.setNextFocusableComponent(btUpdate);
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/010-draw.png"))); // NOI18N
        btUpdate.setToolTipText("Módosít");
        btUpdate.setEnabled(false);
        btUpdate.setNextFocusableComponent(btDel);
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        btDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/012-delete.png"))); // NOI18N
        btDel.setToolTipText("Töröl");
        btDel.setEnabled(false);
        btDel.setNextFocusableComponent(txtRovidNev);
        btDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRovidNev)
                                    .addComponent(txtTeljesNev)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btDel)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAdd, btDel, btUpdate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtRovidNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTeljesNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAdd)
                            .addComponent(btUpdate)
                            .addComponent(btDel)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRovidNevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRovidNevActionPerformed
        
        
    }//GEN-LAST:event_txtRovidNevActionPerformed

    private void txtTeljesNevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeljesNevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeljesNevActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        if (txtRovidNev.getText().isEmpty()) return;
        DB db = new DB();
        db.sqlUjPenznem(txtRovidNev.getText(), txtTeljesNev.getText());
        frissites();
    }//GEN-LAST:event_btAddActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        int id = Integer.parseInt(tbPenznemek.getValueAt(selectionModel.getMinSelectionIndex(), 0).toString());
        int r = selectionModel.getMinSelectionIndex();
        DB db = new DB();
        db.sqlModositPenznem(id, txtRovidNev.getText(), txtTeljesNev.getText());
        frissites();
        tbPenznemek.setRowSelectionInterval(r, r);
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelActionPerformed
        int id = Integer.parseInt(tbPenznemek.getValueAt(selectionModel.getMinSelectionIndex(), 0).toString());
        DB db = new DB();
        db.sqlTorol("penznemek", id);
        frissites();
    }//GEN-LAST:event_btDelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tbPenznemek;
    private javax.swing.JTextField txtRovidNev;
    private javax.swing.JTextField txtTeljesNev;
    // End of variables declaration//GEN-END:variables
}
