/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import ShareManager.DB;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author atna
 */
public class Tozsdek extends Panel {
    ListSelectionModel selectionModel;

    /**
     * Creates new form Tozsdek
     */
    public Tozsdek() {
        initComponents();
        selectionModel = tbTozsdek.getSelectionModel();
        frissites();
        setTableListener();
    }
    
    public void frissites(){
        DB db = new DB();
        db.sqlLekerdezTozsdek(tbTozsdek);
    }
    
    private void setTableListener(){
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if (!selectionModel.isSelectionEmpty()) {
                    btUpdate.setEnabled(true);
                    btDel.setEnabled(true);
                    int i = selectionModel.getMinSelectionIndex();
                    txtRovidNev.setText(tbTozsdek.getValueAt(i, 1).toString());
                    txtTeljesNev.setText(tbTozsdek.getValueAt(i, 2).toString());
                } else {
                    btUpdate.setEnabled(false);
                    btDel.setEnabled(false);
                }
            }
        });
    }
    
    private void hozzaad() {
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbTozsdek = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRovidNev = new javax.swing.JTextField();
        txtTeljesNev = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btDel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(540, 480));

        tbTozsdek.setAutoCreateRowSorter(true);
        tbTozsdek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tőzsde id", "Rövid név", "Teljes név"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbTozsdek);
        if (tbTozsdek.getColumnModel().getColumnCount() > 0) {
            tbTozsdek.getColumnModel().getColumn(0).setMinWidth(0);
            tbTozsdek.getColumnModel().getColumn(0).setPreferredWidth(0);
            tbTozsdek.getColumnModel().getColumn(0).setMaxWidth(0);
            tbTozsdek.getColumnModel().getColumn(0).setHeaderValue("Tőzsde id");
            tbTozsdek.getColumnModel().getColumn(1).setPreferredWidth(30);
            tbTozsdek.getColumnModel().getColumn(1).setHeaderValue("Rövid név");
            tbTozsdek.getColumnModel().getColumn(2).setHeaderValue("Teljes név");
        }

        jLabel2.setText(" Rövid név");

        jLabel3.setText(" Teljes név");

        txtRovidNev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRovidNevActionPerformed(evt);
            }
        });
        txtRovidNev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRovidNevKeyTyped(evt);
            }
        });

        txtTeljesNev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeljesNevActionPerformed(evt);
            }
        });

        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/013-add.png"))); // NOI18N
        btAdd.setToolTipText("Hozzáad");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/010-draw.png"))); // NOI18N
        btUpdate.setToolTipText("Módosít");
        btUpdate.setEnabled(false);
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        btDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/012-delete.png"))); // NOI18N
        btDel.setToolTipText("Töröl");
        btDel.setEnabled(false);
        btDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tőzsdék");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTeljesNev, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(txtRovidNev)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btDel)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAdd, btDel, btUpdate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtRovidNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTeljesNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAdd)
                            .addComponent(btUpdate)
                            .addComponent(btDel)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void txtRovidNevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRovidNevActionPerformed
        
    }//GEN-LAST:event_txtRovidNevActionPerformed

    private void txtTeljesNevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeljesNevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeljesNevActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        if (txtRovidNev.getText().isEmpty()) return;
        DB db = new DB();
        db.sqlUjTozsde(txtRovidNev.getText(), txtTeljesNev.getText());
        frissites();
    }//GEN-LAST:event_btAddActionPerformed

    private void txtRovidNevKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRovidNevKeyTyped
       
       
    }//GEN-LAST:event_txtRovidNevKeyTyped

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        if (txtRovidNev.getText().isEmpty()) return;
        int id = Integer.parseInt(tbTozsdek.getValueAt(selectionModel.getMinSelectionIndex(), 0).toString());
        DB db = new DB();
        db.sqlModositTozsde(id, txtRovidNev.getText(), txtTeljesNev.getText());
        frissites();    
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelActionPerformed
        int id = Integer.parseInt(tbTozsdek.getValueAt(selectionModel.getMinSelectionIndex(), 0).toString());
        DB db = new DB();
        db.sqlTorol("tozsdek", id);
        frissites();
    }//GEN-LAST:event_btDelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tbTozsdek;
    private javax.swing.JTextField txtRovidNev;
    private javax.swing.JTextField txtTeljesNev;
    // End of variables declaration//GEN-END:variables
  
}
