/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import ShareManager.Config;
import ShareManager.DB;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 * @author atna
 */
public class Ugyletek extends Panel {
    ListSelectionModel selectionModel;
    
    /**
     * Creates new form Ertekpapirok
     */
    public Ugyletek() {
        initComponents();
        frissites();
        setTableListener();     
    }

    public void frissites(){
        DB db = new DB();
        db.sqlLekerdezUgyletek(tbUgyletek);
        Config.addItemToComboBox(cbxAccount, Szamlak.tbSzamlak);
        Config.addItemToComboBox(cbxExchange, Tozsdek.tbTozsdek);
        ertekpapirFrissites();
        szamol();
    }
    
    private void ertekpapirFrissites(){
        if (chbFilter.isSelected()) 
            Config.addItemToComboBox(cbxShare, Ertekpapirok.tbErtekpapirok, cbxExchange.getSelectedItem());
        else Config.addItemToComboBox(cbxShare, Ertekpapirok.tbErtekpapirok);
    }
    
    private void megjelenit(boolean b){
            lbValue2.setVisible(b);
            lbCurrency2.setVisible(b);
        }
    
    private void szamol(){
        double x;
        if (rbtBuy.isSelected()) x=1;
        else if (rbtSell.isSelected()) x=-1;
        else return;
        x *= Double.parseDouble(spPrice.getValue().toString()) * Double.parseDouble(spQuantity.getValue().toString());
        lbValue1.setText(String.format("%1$,.2f", x));
        if (!lbCurrency1.getText().equals("HUF")) {
            x *= Double.parseDouble(spCurrencyPrice.getValue().toString());
            lbValue2.setText(String.format("%1$,.2f", x));
            megjelenit(true);
        } else {
            megjelenit(false);
        }
    }
    
    private String[] sqlAdatok(){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        int q=Integer.parseInt(spQuantity.getValue().toString());
        if (rbtSell.isSelected()) q*=-1;
        else if (rbtBuy.isSelected()) q *= 1;
        
        String[] s = {Config.getID(Ertekpapirok.tbErtekpapirok, cbxShare.getSelectedItem()),
                    Config.getID(Szamlak.tbSzamlak, cbxAccount.getSelectedItem()),
                    ""+q,
                    spPrice.getValue().toString(),
                    sdf.format(spDate.getValue()),
                    spCommission.getValue().toString(),
                    spCurrencyPrice.getValue().toString()
        };
        return s;
    }
    
    private void setTableListener(){
        selectionModel = tbUgyletek.getSelectionModel();
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if (!selectionModel.isSelectionEmpty()) {
                    btUpdate.setEnabled(true);
                    btDel.setEnabled(true);
                    int i = selectionModel.getMinSelectionIndex();
                    chbFilter.setSelected(false);
                    cbxShare.setSelectedItem(tbUgyletek.getValueAt(i, 1));
                    cbxAccount.setSelectedItem(tbUgyletek.getValueAt(i, 2).toString());
                    spQuantity.setValue(Math.abs(Integer.parseInt(tbUgyletek.getValueAt(i, 3).toString())));
                    if (Double.parseDouble(tbUgyletek.getValueAt(i, 3).toString())>0) rbtBuy.setSelected(true);
                    else rbtSell.setSelected(true);
                    spPrice.setValue(Double.parseDouble(tbUgyletek.getValueAt(i, 4).toString()));
                    spDate.setValue(Date.valueOf(tbUgyletek.getValueAt(i, 5).toString()));
                    spCommission.setValue(Double.parseDouble(tbUgyletek.getValueAt(i, 6).toString()));
                    spCurrencyPrice.setValue(Double.parseDouble(tbUgyletek.getValueAt(i, 7).toString()));
                } else {
                    btUpdate.setEnabled(false);
                    btDel.setEnabled(false);
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbxShare = new javax.swing.JComboBox<>();
        cbxAccount = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btAdd = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUgyletek = new javax.swing.JTable();
        btDel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        spQuantity = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        spDate = new javax.swing.JSpinner();
        spCommission = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spPrice = new javax.swing.JSpinner();
        lbValue1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbCurrency1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        chbFilter = new javax.swing.JCheckBox();
        cbxExchange = new javax.swing.JComboBox<>();
        rbtBuy = new javax.swing.JRadioButton();
        rbtSell = new javax.swing.JRadioButton();
        lbCurrency2 = new javax.swing.JLabel();
        lbValue2 = new javax.swing.JLabel();
        spCurrencyPrice = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(780, 560));
        setPreferredSize(new java.awt.Dimension(780, 530));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Értékpapír");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel8.setText("Számla");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        cbxShare.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxShareItemStateChanged(evt);
            }
        });
        cbxShare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxShareActionPerformed(evt);
            }
        });
        add(cbxShare, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 115, -1));
        add(cbxAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 115, -1));

        jLabel11.setText("Mennyiség");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel10.setText("Jutalék");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/013-add.png"))); // NOI18N
        btAdd.setMnemonic('o');
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 66, -1));

        btUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/010-draw.png"))); // NOI18N
        btUpdate.setMnemonic('m');
        btUpdate.setToolTipText("");
        btUpdate.setEnabled(false);
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        add(btUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 66, -1));

        tbUgyletek.setAutoCreateRowSorter(true);
        tbUgyletek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ügylet ID", "Értékpapír", "Számla", "Mennyiség", "Árfolyam", "Dátum", "Jutalék", "Dev.árf"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbUgyletek);
        if (tbUgyletek.getColumnModel().getColumnCount() > 0) {
            tbUgyletek.getColumnModel().getColumn(0).setMinWidth(0);
            tbUgyletek.getColumnModel().getColumn(0).setPreferredWidth(0);
            tbUgyletek.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 44, 540, 470));

        btDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/012-delete.png"))); // NOI18N
        btDel.setMnemonic('m');
        btDel.setEnabled(false);
        btDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelActionPerformed(evt);
            }
        });
        add(btDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 66, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ügyletek");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 760, -1));

        spQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spQuantity.setEditor(new javax.swing.JSpinner.NumberEditor(spQuantity, ""));
        spQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spQuantityStateChanged(evt);
            }
        });
        add(spQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 115, -1));

        jLabel1.setText("Dátum");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        spDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        spDate.setEditor(new javax.swing.JSpinner.DateEditor(spDate, "yyyy-MM-dd"));
        add(spDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 114, -1));

        spCommission.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        add(spCommission, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 114, -1));

        jLabel2.setText("Árfolyam");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        spPrice.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0E-5d, null, 1.0d));
        spPrice.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spPriceStateChanged(evt);
            }
        });
        add(spPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 115, -1));

        lbValue1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbValue1.setText("-");
        lbValue1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lbValue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 102, -1));

        jLabel5.setText("Érték");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 60, -1));

        lbCurrency1.setText("-");
        add(lbCurrency1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 196, 9));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Szűrő"));

        chbFilter.setText("Tőzsde");
        chbFilter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbFilterItemStateChanged(evt);
            }
        });
        chbFilter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbFilterStateChanged(evt);
            }
        });
        chbFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbFilterActionPerformed(evt);
            }
        });
        jPanel1.add(chbFilter);

        cbxExchange.setEnabled(false);
        cbxExchange.setMaximumSize(new java.awt.Dimension(110, 25));
        cbxExchange.setMinimumSize(new java.awt.Dimension(110, 25));
        cbxExchange.setPreferredSize(new java.awt.Dimension(110, 25));
        cbxExchange.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxExchangeItemStateChanged(evt);
            }
        });
        jPanel1.add(cbxExchange);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 44, -1, -1));

        buttonGroup1.add(rbtBuy);
        rbtBuy.setText("Vétel");
        rbtBuy.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtBuyStateChanged(evt);
            }
        });
        add(rbtBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        buttonGroup1.add(rbtSell);
        rbtSell.setText("Eladás");
        rbtSell.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtSellStateChanged(evt);
            }
        });
        add(rbtSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        lbCurrency2.setText("HUF");
        add(lbCurrency2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        lbValue2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbValue2.setText("-");
        lbValue2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lbValue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 102, -1));

        spCurrencyPrice.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, null, 1.0d));
        spCurrencyPrice.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spCurrencyPriceStateChanged(evt);
            }
        });
        add(spCurrencyPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 114, -1));

        jLabel12.setText("Deviza árf.");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        
        int id = Integer.parseInt(tbUgyletek.getValueAt(selectionModel.getMinSelectionIndex(), 0).toString());
        
        DB db = new DB();
        db.sqlModositUgylet(id, sqlAdatok());
        frissites();     
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        if (!rbtBuy.isSelected() && !rbtSell.isSelected()) return;
          
        DB db = new DB();
        db.sqlUjUgylet(sqlAdatok());
        frissites();     
    }//GEN-LAST:event_btAddActionPerformed

    private void btDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelActionPerformed
        int id = Integer.parseInt(tbUgyletek.getValueAt(selectionModel.getMinSelectionIndex(), 0).toString());
        DB db = new DB();
        db.sqlTorol("ugyletek", id);
        frissites();
    }//GEN-LAST:event_btDelActionPerformed

    private void chbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbFilterActionPerformed

    private void chbFilterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chbFilterStateChanged
        
    }//GEN-LAST:event_chbFilterStateChanged

    private void chbFilterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbFilterItemStateChanged
        cbxExchange.setEnabled(chbFilter.isSelected()); //a tőszde szűrő aktiv/inaktív
        ertekpapirFrissites();
    }//GEN-LAST:event_chbFilterItemStateChanged

    private void cbxExchangeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxExchangeItemStateChanged
       ertekpapirFrissites();
    }//GEN-LAST:event_cbxExchangeItemStateChanged

    private void cbxShareItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxShareItemStateChanged
        String s = Config.getObject(Ertekpapirok.tbErtekpapirok, cbxShare.getSelectedItem(), 6);
        lbCurrency1.setText(s);
    }//GEN-LAST:event_cbxShareItemStateChanged

    private void spQuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spQuantityStateChanged
        szamol();
    }//GEN-LAST:event_spQuantityStateChanged

    private void spPriceStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spPriceStateChanged
        szamol();
    }//GEN-LAST:event_spPriceStateChanged

    private void rbtBuyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtBuyStateChanged
        szamol();
    }//GEN-LAST:event_rbtBuyStateChanged

    private void rbtSellStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtSellStateChanged
        szamol();
    }//GEN-LAST:event_rbtSellStateChanged

    private void cbxShareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxShareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxShareActionPerformed

    private void spCurrencyPriceStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spCurrencyPriceStateChanged
        szamol();
    }//GEN-LAST:event_spCurrencyPriceStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxAccount;
    private javax.swing.JComboBox<String> cbxExchange;
    private javax.swing.JComboBox<String> cbxShare;
    private javax.swing.JCheckBox chbFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbCurrency1;
    private javax.swing.JLabel lbCurrency2;
    private javax.swing.JLabel lbValue1;
    private javax.swing.JLabel lbValue2;
    private javax.swing.JRadioButton rbtBuy;
    private javax.swing.JRadioButton rbtSell;
    private javax.swing.JSpinner spCommission;
    private javax.swing.JSpinner spCurrencyPrice;
    private javax.swing.JSpinner spDate;
    private javax.swing.JSpinner spPrice;
    private javax.swing.JSpinner spQuantity;
    private javax.swing.JTable tbUgyletek;
    // End of variables declaration//GEN-END:variables
}
